import { useState } from "react";
import ComboSingle from "../inputs/ComboSingle";
import InputNumber from "../inputs/InputNumber";

export default function UnitConverter() {
  const [quantity, setQuantity] = useState<number>(1);
  const [selected, setSelected] = useState<string>("");

  return (
    <>
      <div className="flex w-full flex-row items-center gap-2">
        <InputNumber value={quantity} setValue={setQuantity} />
        {options[selected]?.[2] ?? "Cup"}
        {quantity === 1 ? " " : "s "}
        de
      </div>
      <ComboSingle
        options={Object.keys(options).map((e) => ({ name: e }))}
        value={{ name: selected }}
        setValue={(e) => setSelected(e?.name ?? "")}
      />
      <div className="bg-base-content h-0.5 w-full" />
      <span className="ml-auto text-xl font-semibold">
        {"= " +
          (options[selected]
            ? (options[selected][1] * quantity) / options[selected][0]
            : 0) +
          " Gramas"}
      </span>
    </>
  );
}

// <Name, [Original Amount, Equivalent in Grams, Original Unit (default is Cups)]>
const options: Record<string, [number, number, string?]> = {
  "Farinha '00' para Pizza": [1, 116],
  "Xarope de Agave": [0.25, 84],
  "Mistura para Bolos Multiusos": [1, 120],
  "Farinha Multiusos": [1, 120],
  "Manteiga de Amêndoa": [0.25, 68],
  "Farinha de Amêndoa": [1, 96],
  "Farinha de Amêndoa Moída": [1, 84],
  "Pasta de Amêndoa (Compactada)": [1, 259],
  "Amêndoas (Fatiadas)": [0.5, 43],
  "Amêndoas (Lasca)": [0.5, 57],
  "Amêndoas Inteiras (com Casca)": [1, 142],
  "Farinha de Amaranto": [1, 103],
  "Concentrado de Sumo de Maçã": [0.25, 70],
  "Maçãs (Secas e Cortadas)": [1, 85],
  "Maçãs (Descascadas e Fatiadas)": [1, 113],
  "Puré de Maçã (Applesauce)": [1, 255],
  "Alperces (Secas e Cortadas)": [0.5, 64],
  "Farinha para Pão Artesanal": [1, 120],
  "Cobertura para Pão Artesanal": [0.25, 43],
  "Recheio de Canela para Padeiro": [1, 152],
  "Mistura de Frutas para Padeiro": [1, 128],
  "Açúcar Fino para Padeiro (Açúcar Superfino, Açúcar de Confeiteiro)": [
    1, 190,
  ],
  "Fermento em Pó": [1, 4, "Teaspoon"],
  "Bicarbonato de Sódio": [0.5, 3, "Teaspoon"],
  "Adoçante para Bolos": [1, 170],
  "Bananas (Amassadas)": [1, 227],
  "Cevada Cozida": [1, 215],
  "Cevada Perlada": [1, 213],
  "Flocos de Cevada": [0.5, 46],
  "Farinha de Cevada": [1, 85],
  "Xarope de Malte de Cevada": [2, 42, "Tablespoon"],
  "Pesto de Manjericão": [2, 28, "Tablespoon"],
  "Pimentos (Frescos)": [1, 142],
  "Frutos Vermelhos (Congelados)": [1, 142],
  "Pó de Queijo Cheddar Melhorado": [0.5, 57],
  "Mirtilos (Secos)": [1, 156],
  "Mirtilos (Frescos ou Congelados)": [0.75, 140],
  "Sumo de Mirtilo": [1, 241],
  "Sidra Cozida": [0.25, 85],
  "Cereal de Farelo": [1, 60],
  "Farinha de Pão Ralado (Seca)": [0.25, 28],
  "Farinha de Pão Ralado (Fresca)": [0.25, 21],
  "Pão Ralado Japonês Panko": [1, 50],
  "Farinha para Pão": [1, 120],
  "Arroz Integral Cozido": [1, 170],
  "Farinha de Arroz Integral": [1, 128],
  "Açúcar Mascavado (Escuro ou Claro, Compactado)": [1, 213],
  "Trigo Sarraceno Inteiro": [1, 170],
  "Farinha de Trigo Sarraceno": [1, 120],
  Bulgur: [1, 152],
  Manteiga: [0.5, 113],
  Leitelho: [1, 227],
  "Mistura para Bolachas com Leitelho": [1, 110],
  "Leite em Pó com Leitelho": [2, 18, "Tablespoon"],
  "Nibs de Cacau": [1, 120],
  "Melhorador para Bolos": [2, 14, "Tablespoon"],
  "Casca de Limão Cristalizada": [0.25, 37],
  "Casca de Laranja Cristalizada": [0.25, 25],
  'Caramelo (14-16 Pedaços Individuais, Quadrados de 1")': [0.5, 142],
  "Pedaços de Caramelo ou Toffee Picados": [1, 156],
  "Sementes de Alcaravia": [2, 18, "Tablespoon"],
  "Cenouras (Cozidas e Puré)": [0.5, 128],
  "Cenouras (Cortadas)": [1, 142],
  "Cenouras (Raladas)": [1, 99],
  "Cajus (Picados)": [1, 113],
  "Cajus (Inteiros)": [1, 113],
  "Aipo (Cortado)": [1, 142],
  "Queijo Feta": [0.5, 57],
  "Queijo Ralado Cheddar, Jack, Mozzarella ou Suíço": [1, 113],
  "Queijo Ralado Parmesão": [0.5, 50],
  "Queijo Ricota": [1, 227],
  "Cerejas Cristalizadas": [0.25, 50],
  "Cerejas Secas": [0.5, 71],
  "Cerejas Frescas (Descaroçadas e Picadas)": [0.5, 80],
  "Cerejas Congeladas": [1, 113],
  "Concentrado de Cereja": [2, 42, "Tablespoon"],
  "Sementes de Chia": [0.25, 37],
  "Farinha de Grão-de-Bico": [1, 85],
  "Cebolinho Fresco": [0.5, 21],
  "Chocolate Picado": [1, 170],
  "Gotas de Chocolate": [1, 170],
  "Pedaços de Chocolate": [1, 170],
  "Mistura para Mousse de Chocolate": [0.25, 28],
  "Pedaços Doces de Canela": [0.25, 35],
  "Açúcar com Canela": [0.25, 50],
  "Farinha Climate Blend": [1, 115],
  "Cacau em Pó (Não Adoçado)": [0.5, 42],
  "Coco Ralado Adoçado": [1, 85],
  "Coco Torrado": [1, 85],
  "Coco Desidratado sem Açúcar": [1, 85],
  "Flocos Grandes de Coco sem Açúcar": [1, 60],
  "Coco Ralado sem Açúcar": [1, 53],
  "Creme de Coco sem Açúcar": [1, 284],
  "Farinha de Coco": [1, 128],
  "Leite de Coco Enlatado, Bem Agitado": [1, 241],
  "Leite de Coco Evaporado": [1, 242],
  "Leite de Coco em Pó": [0.5, 57],
  "Óleo de Coco": [0.5, 113],
  "Açúcar de Coco": [0.5, 77],
  "Açúcar em Pó (Não Peneirado)": [2, 227],
  "Manteiga de Bolacha": [0.25, 72],
  "Biscoitos Esmagados": [1, 85],
  "Milho (Fresco ou Congelado)": [0.25, 38],
  "Milho Estourado": [4, 21],
  "Xarope de Milho": [1, 312],
  "Fubá (Integral)": [1, 138],
  "Fubá Amarelo (Quaker)": [1, 156],
  "Amido de Milho": [0.25, 28],
  "Queijo Cottage": [0.5, 113],
  "Trigo Partido": [1, 149],
  "Oxicoco Seco": [0.5, 57],
  "Oxicoco Fresco ou Congelado": [1, 99],
  "Natas (Nata Espessa, Nata Ligeira ou Meio-Gordo)": [1, 227],
  "Queijo Creme": [1, 227],
  "Creme de Coco": [0.5, 142],
  "Crème Fraîche": [0.5, 124],
  "Gengibre Cristalizado": [0.5, 92],
  Groselhas: [1, 142],
  "Tâmaras (Picadas)": [1, 149],
  "Açúcar Demerara": [1, 220],
  "Pó de Mirtilo Seco": [0.25, 28],
  "Leite Seco para Padeiro": [0.25, 28],
  "Leite Magro Seco em Pó": [0.25, 28],
  "Flocos de Batata Seca (Puré Instantâneo)": [0.5, 43],
  "Leite Seco Integral": [0.5, 50],
  "Farinha de Trigo Duro": [1, 124],
  "Melhorador para Massa Fácil": [2, 18, "Tablespoon"],
  "Pó de Café Espresso": [1, 7, "Tablespoon"],
  'Cobertura de "Everything Bagel"': [0.25, 35],
  "Figos (Secos, Picados)": [1, 149],
  "Farinha First Clear": [1, 106],
  "Farelo de Linho": [0.5, 50],
  "Semente de Linho": [0.25, 35],
  "Mistura de Queijo e Ervas Formaggio Italiano": [0.25, 30],
  "Farinha Estilo Francês": [1, 120],
  "Mistura de Frutas para Bolo de Frutas": [1, 120],
  "Alho (Picado)": [2, 28, "Tablespoons"],
  "Alho (Descascado e Fatiado)": [1, 149],
  Ghee: [0.25, 44],
  "Gengibre (Fresco, Fatiado)": [0.25, 57],
  "Farinha de Pizza sem Glúten": [1, 100],
  "Mistura de Panificação sem Glúten para todos os fins": [1, 120],
  "Farinha sem Glúten para todos os fins": [1, 156],
  "Farinha de Pão sem Glúten": [1, 120],
  "Farinha sem Glúten medida para medida": [1, 120],
  "Fermento Natural sem Glúten (feito com farinha de pão sem glúten)": [1, 170],
  "Fermento Natural sem Glúten (feito com farinha sem glúten medida para medida)":
    [1, 227],
  "Farinha de Arroz Glutinoso": [1, 120],
  "Farinha de Trigo Dourado": [1, 113],
  "Migalhas (Crumble) de Biscoito Graham": [1, 100],
  Granola: [1, 113],
  "Grape Nuts": [0.5, 57],
  "Pasta de Goiaba": [0.25, 100],
  "Mistura de Grãos de Colheita": [0.5, 74],
  "Farinha de Avelã": [1, 89],
  "Pasta de Avelã Pralinada": [0.5, 156],
  "Pasta de Avelã": [0.5, 160],
  "Avelãs (Inteiras)": [1, 142],
  "Fibra Natural Hi-Maize": [0.25, 32],
  "Farinha de Glúten Alto": [1, 120],
  Mel: [1, 21, "Tablespoon"],
  "Instant ClearJel": [1, 11, "Tablespoon"],
  "Farinha Estilo Irlandês": [1, 110],
  "Farinha Estilo Italiano": [1, 106],
  "Geleia ou Compota": [0.25, 85],
  "Jammy Bits": [1, 184],
  "Farinha de Trigo Cetogênica": [1, 120],
  "Mistura para Crosta de Pizza de Trigo Cetogênica": [1, 110],
  "Suco de Lima": [1, 227],
  Banha: [0.5, 113],
  "Alho-poró (Picado)": [1, 92],
  "Migalhas (Crumble) de Limão": [1, 180],
  "Creme de Limão": [0.5, 113],
  "Suco de Limão": [1, 14, "Tablespoon"],
  "Pó de Suco de Limão": [2, 18, "Tablespoon"],
  "Pó de Suco de Lima": [2, 18, "Tablespoon"],
  "Nozes de Macadâmia (Inteiras)": [1, 149],
  "Xarope de Malte": [2, 43, "Tablespoon"],
  "Pó de Leite Maltado": [0.25, 35],
  "Flocos de Trigo Maltado": [0.5, 64],
  "Açúcar de Canela e Baga de Maple para Torrada Francesa": [0.25, 48],
  "Açúcar de Maple": [0.5, 78],
  "Xarope de Maple": [0.5, 156],
  "Pasta de Marshmallow Caseira": [1, 72],
  "Pasta de Marshmallow Comprada": [1, 123],
  "Marshmallow Fluff®": [1, 128],
  "Marshmallows (Mini)": [1, 43],
  Marzipã: [1, 290],
  "Masa Harina": [1, 93],
  "Queijo Mascarpone": [1, 227],
  "Puré de Batata": [1, 213],
  "Puré de Batata Doce": [1, 240],
  Maionese: [0.5, 113],
  "Farinha de Centeio Média": [1, 106],
  "Pó de Merengue": [0.25, 43],
  "Leite (Evaporado)": [0.5, 113],
  "Leite (Fresco)": [1, 227],
  "Painço (Inteiro)": [0.5, 103],
  "Mini Pepitas de Chocolate": [1, 177],
  Melaço: [0.25, 85],
  "Cogumelos (Fatiados)": [1, 78],
  "Pó de Malte Não Diastático": [2, 18, "Tablespoon"],
  Nutella: [0.5, 149],
  "Farelo de Aveia": [0.5, 53],
  "Farinha de Aveia": [1, 92],
  "Aveia (King Arthur Rolled)": [1, 113],
  "Aveia (Tradicional ou de Cozimento Rápido)": [1, 89],
  "Aveia (Preparada)": [1, 147],
  "Óleo de Oliva": [0.25, 50],
  "Azeitonas (Fatiadas)": [1, 142],
  "Cebolas (Frescas, Picadas)": [1, 142],
  "Farinha de Panificação Paleo": [1, 104],
  "Banha de Palma": [0.25, 45],
  "Puré de Maracujá": [0.33, 60],
  "Mistura de Farinha para Massa": [1, 145],
  "Farinha para Pastelaria": [1, 106],
  "Mistura de Farinha para Pastelaria": [1, 113],
  "Pêssegos (Descascados e Picados)": [1, 170],
  "Manteiga de Amendoim": [0.5, 135],
  "Amendoins (Inteiros, Descascados)": [1, 142],
  "Pêras (Descascadas e Picadas)": [1, 163],
  "Farelo de Pecã": [1, 80],
  "Pecãs (picadas)": [0.5, 57],
  "Pecãs (inteiras)": [1, 105],
  "Melhorador de Recheio de Torta": [0.25, 46],
  Pinhões: [0.5, 71],
  "Ananás (Esmagado, Escorrido)": [1, 256],
  "Ananás (Seco)": [0.5, 71],
  "Ananás (Fresco ou Enlatado, Picado)": [1, 170],
  "Nozes de Pistache (Descascadas)": [0.5, 60],
  "Pasta de Pistache": [0.25, 78],
  "Tempero para Massa de Pizza": [2, 12, "Tablespoon"],
  "Mistura de Farinha para Pizza": [1, 124],
  "Molho de Pizza": [0.25, 57],
  "Tempero para Pizza": [2, 10, "Tablespoon"],
  Polenta: [1, 163],
  "Sementes de Papoila": [2, 18, "Tablespoon"],
  "Farinha de Batata": [0.25, 46],
  "Amido de Batata": [1, 152],
  "Farinha de Centeio Pumpernickel": [1, 106],
  "Purê de Abóbora": [1, 227],
  "Sementes de Abóbora": [0.25, 40],
  "Queijo Fresco": [0.5, 57],
  "Quinoa (Cozida)": [1, 184],
  "Quinoa (Inteira)": [1, 177],
  "Farinha de Quinoa": [1, 110],
  "Passas (Soltas)": [1, 149],
  "Passas (Compactadas)": [0.5, 85],
  "Framboesas (Frescas)": [1, 120],
  'Ruibarbo (Fatiado, Fatias de 1/2")': [1, 120],
  "Arroz (Grão Longo, Seco)": [0.5, 99],
  "Farinha de Arroz (Branca)": [1, 142],
  "Rice Krispies": [1, 28],
  "Melhorador de Pão de Venteio": [2, 14, "Tablespoon"],
  "Rye Chops": [1, 120],
  "Flocos de Centeio": [1, 124],
  "Mistura de Farinha de Centeio": [1, 106],
  "Sal (Kosher, Diamond Crystal)": [1, 8, "Tablespoon"],
  "Sal (Kosher, Morton's)": [1, 16, "Tablespoon"],
  "Sal (de Mesa)": [1, 18, "Tablespoon"],
  "Cebolinha (Fatiada)": [1, 64],
  "Farinha Auto-Fermentável": [1, 113],
  "Farinha de Sêmola": [1, 163],
  "Sementes de Gergelim": [0.5, 71],
  "Chalotas (Descascadas e Fatiadas)": [1, 156],
  "Mistura de Seis Grãos": [1, 128],
  "Açúcar Branca de Neve não derretível para cobertura": [0.5, 57],
  "Farinha de Sorgo": [1, 138],
  "Creme de Leite Azedo": [1, 227],
  "Fermento Natural": [1, 227],
  "Farinha de Soja": [0.25, 35],
  "Açúcar Brilhante": [0.25, 57],
  "Farinha de Espelta": [1, 99],
  "Farinha de Trigo Brotado": [1, 113],
  "Aveia em Flocos de Aço": [0.5, 70],
  "Açúcar para Pão Doce": [1, 99],
  "Morangos (Frescos Fatiados)": [1, 167],
  "Açúcar (Granulado Branco)": [1, 198],
  "Substituto de Açúcar (Splenda)": [1, 25],
  "Tomates Secos ao Sol (Embalagem Seca)": [1, 170],
  "Sementes de Girassol": [0.25, 35],
  "Mistura Super 10": [1, 106],
  "Açúcar Pérola Sueco": [0.25, 49],
  "Leite de Coco Condensado Adoçado": [1, 288],
  "Leite Condensado Adoçado": [0.25, 78],
  "Pasta de Tahini": [0.5, 128],
  "Amido ou Farinha de Tapioca": [1, 113],
  "Tapioca (Cozimento Rápido)": [2, 21, "Tablespoon"],
  "Farinha de Teff": [1, 135],
  "The Works Cobertura para Pão": [0.25, 35],
  "Farinha de Amêndoa Torrada": [1, 96],
  "Pedacinhos de Toffee": [1, 156],
  "Pasta de Tomate": [2, 29, "Tablespoon"],
  "Mistura de Frutas Tropicais": [1, 128],
  "Açúcar Turbinado (Cru)": [1, 180],
  "Farinha de Bolo sem Alvejante": [1, 120],
  "Extrato de Baunilha": [1, 14, "Tablespoon"],
  "Óleo Vegetal": [1, 198],
  "Banha Vegetal": [0.25, 46],
  "Glúten de Trigo Vital": [2, 18, "Tablespoon"],
  "Nozes (Picadas)": [1, 113],
  "Nozes (Inteiras)": [0.5, 64],
  Água: [1, 227],
  "Bagas de Trigo (Vermelhas)": [1, 184],
  "Farelo de Trigo": [0.5, 32],
  "Gérmen de Trigo": [0.25, 28],
  "Pepitas de Chocolate Branco": [1, 170],
  "Farinha de Centeio Branca": [1, 106],
  "Mistura de Farinha de Grão Inteiro": [1, 113],
  "Farinha de Trigo Integral (Premium 100%)": [1, 113],
  "Farinha de Trigo Integral para Massa / Farinha de Graham": [1, 96],
  "Fermento (Instantâneo, Teaspoon)": [2, 6, ""],
  "Fermento (Instantâneo, Tablespoon)": [1, 9, ""],
  Iogurte: [1, 227],
  "Mistura de frutas Yuletide Cheer": [1, 130],
  "Abobrinha (ralada)": [1, 121],
};
